// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:analyzer/file_system/file_system.dart';
import 'package:dartdoc_vitepress/src/generator/generator.dart';
import 'package:dartdoc_vitepress/src/generator/resource_loader.dart';
import 'package:path/path.dart' as p;

/// Generates initial Jaspr project scaffold files.
///
/// Creates the following files (only if they don't already exist):
/// - `pubspec.yaml` with Jaspr dependencies
/// - `lib/main.server.dart` with ContentApp configuration
/// - `lib/main.client.dart` for client-side hydration
/// - `content/index.md` homepage
///
/// Templates are stored in `lib/resources/jaspr/`.
class JasprInitGenerator {
  final FileWriter writer;
  final ResourceProvider resourceProvider;
  final String outputPath;

  static const _templatePrefix = 'package:dartdoc_vitepress/resources/jaspr';

  JasprInitGenerator({
    required this.writer,
    required this.resourceProvider,
    required this.outputPath,
  });

  /// Generates scaffold files. Only creates files that don't exist.
  Future<void> generate({
    required String packageName,
    String repositoryUrl = '',
  }) async {
    final safeName = packageName
        .replaceAll(RegExp(r'[^a-zA-Z0-9_-]'), '-')
        .toLowerCase();
    final placeholders = {
      '{{packageName}}': packageName,
      '{{safePackageName}}': safeName,
      '{{repositoryUrl}}': repositoryUrl,
    };

    final templateDir =
        (await resourceProvider.getResourceFolder(_templatePrefix)).path;

    _writeTemplateIfAbsent(
      templateDir: templateDir,
      templateFile: 'pubspec.yaml',
      outputFile: 'pubspec.yaml',
      placeholders: placeholders,
    );
    _writeTemplateIfAbsent(
      templateDir: templateDir,
      templateFile: p.join('lib', 'main.server.dart'),
      outputFile: 'lib/main.server.dart',
      placeholders: placeholders,
    );
    _writeTemplateIfAbsent(
      templateDir: templateDir,
      templateFile: p.join('lib', 'main.client.dart'),
      outputFile: 'lib/main.client.dart',
      placeholders: placeholders,
    );
    _writeTemplateIfAbsent(
      templateDir: templateDir,
      templateFile: p.join('content', 'index.md'),
      outputFile: 'content/index.md',
      placeholders: placeholders,
    );
    _writeTemplateIfAbsent(
      templateDir: templateDir,
      templateFile: '.gitignore',
      outputFile: '.gitignore',
      placeholders: placeholders,
    );

    // Generate empty sidebar stub so the app compiles before first generation.
    _writeFileToDisk(
      outputFile: 'lib/generated/api_sidebar.dart',
      content:
          '// Generated by dartdoc_vitepress. Do not edit.\n'
          'const apiSidebarGroups = <dynamic>[];\n',
    );
    _writeFileToDisk(
      outputFile: 'lib/generated/guide_sidebar.dart',
      content:
          '// Generated by dartdoc_vitepress. Do not edit.\n'
          'const guideSidebarGroups = <dynamic>[];\n',
    );
  }

  void _writeFileToDisk({
    required String outputFile,
    required String content,
  }) {
    final fullOutputPath = p.normalize(p.join(outputPath, outputFile));
    final existingFile = resourceProvider.getFile(fullOutputPath);
    if (existingFile.exists) return;

    final parent = existingFile.parent;
    if (!parent.exists) parent.create();
    existingFile.writeAsStringSync(content);
  }

  void _writeTemplateIfAbsent({
    required String templateDir,
    required String templateFile,
    required String outputFile,
    required Map<String, String> placeholders,
  }) {
    final fullOutputPath = p.normalize(p.join(outputPath, outputFile));
    final existingFile = resourceProvider.getFile(fullOutputPath);
    if (existingFile.exists) return;

    final templatePath = p.join(templateDir, templateFile);
    var content = resourceProvider.getFile(templatePath).readAsStringSync();

    for (final entry in placeholders.entries) {
      content = content.replaceAll(entry.key, entry.value);
    }

    writer.write(outputFile, content);
  }
}
