// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:dartdoc_vitepress/src/generator/core/guide_collection.dart'
    as guide_core;
import 'package:dartdoc_vitepress/src/generator/jaspr/paths.dart';
import 'package:dartdoc_vitepress/src/model/model.dart';

/// Generates a Dart sidebar data file for Jaspr documentation sites.
class JasprSidebarGenerator {
  final JasprPathResolver _paths;

  JasprSidebarGenerator(this._paths);

  /// Generates API sidebar Dart source from the [PackageGraph].
  String generateApi(PackageGraph packageGraph) {
    final buf = StringBuffer();
    _writeHeader(buf);
    buf.writeln('const apiSidebarGroups = <SidebarGroup>[');

    for (final package in packageGraph.localPackages) {
      final libraries = package.publicLibrariesSorted
          .where((lib) =>
              !isDuplicateSdkLibrary(lib, package.libraries) &&
              !isInternalSdkLibrary(lib) &&
              _hasApiElements(lib))
          .toList()
        ..sort((a, b) => a.name.compareTo(b.name));

      if (libraries.isEmpty) continue;

      final isMultiPackage = packageGraph.localPackages.length > 1;
      _writeGroup(
        buf,
        title: isMultiPackage ? package.name : null,
        items: [
          for (final lib in libraries)
            if (_paths.urlFor(lib) case final url?)
              (
                text: lib.name,
                link: url,
              ),
        ],
      );
    }

    buf.writeln('];');
    return buf.toString();
  }

  /// Generates guide sidebar Dart source from collected guide [entries].
  String generateGuide(
    List<guide_core.GuideEntry> entries, {
    required bool isMultiPackage,
  }) {
    final buf = StringBuffer();
    _writeHeader(buf);
    buf.writeln('const guideSidebarGroups = <SidebarGroup>[');

    if (isMultiPackage) {
      final byPackage = <String, List<guide_core.GuideEntry>>{};
      for (final entry in entries) {
        byPackage.putIfAbsent(entry.packageName, () => []).add(entry);
      }

      for (final packageName in byPackage.keys.toList()..sort()) {
        final sorted = guide_core.sortGuideEntries(byPackage[packageName]!);
        _writeGroup(
          buf,
          title: packageName,
          items: [
            for (final entry in sorted)
              (
                text: entry.title,
                link: '/${entry.relativePath}'.replaceAll('.md', ''),
              ),
          ],
        );
      }
    } else {
      final sorted = guide_core.sortGuideEntries(entries);
      if (sorted.isNotEmpty) {
        _writeGroup(
          buf,
          items: [
            for (final entry in sorted)
              (
                text: entry.title,
                link: '/${entry.relativePath}'.replaceAll('.md', ''),
              ),
          ],
        );
      }
    }

    buf.writeln('];');
    return buf.toString();
  }

  void _writeHeader(StringBuffer buf) {
    buf.writeln('// Generated by dartdoc_vitepress. Do not edit.');
    buf.writeln('// ignore_for_file: constant_identifier_names');
    buf.writeln();
    buf.writeln('class SidebarItem {');
    buf.writeln('  final String text;');
    buf.writeln('  final String link;');
    buf.writeln(
        '  const SidebarItem({required this.text, required this.link});');
    buf.writeln('}');
    buf.writeln();
    buf.writeln('class SidebarGroup {');
    buf.writeln('  final String? title;');
    buf.writeln('  final List<SidebarItem> items;');
    buf.writeln('  const SidebarGroup({this.title, required this.items});');
    buf.writeln('}');
    buf.writeln();
  }

  void _writeGroup(
    StringBuffer buf, {
    required List<({String text, String link})> items,
    String? title,
  }) {
    if (items.isEmpty) return;
    buf.writeln('  SidebarGroup(');
    if (title != null) {
      buf.writeln("    title: '${_esc(title)}',");
    }
    buf.writeln('    items: [');
    for (final item in items) {
      buf.writeln(
        "      SidebarItem(text: '${_esc(item.text)}', link: '${_esc(item.link)}'),",
      );
    }
    buf.writeln('    ],');
    buf.writeln('  ),');
  }

  static String _esc(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

  static bool _hasApiElements(Library library) {
    return library.publicClassesSorted.isNotEmpty ||
        library.publicExceptionsSorted.isNotEmpty ||
        library.publicEnumsSorted.isNotEmpty ||
        library.publicMixinsSorted.isNotEmpty ||
        library.publicExtensionsSorted.isNotEmpty ||
        library.publicExtensionTypesSorted.isNotEmpty ||
        library.publicFunctionsSorted.isNotEmpty ||
        library.publicPropertiesSorted.isNotEmpty ||
        library.publicConstantsSorted.isNotEmpty ||
        library.publicTypedefsSorted.isNotEmpty;
  }
}
