// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:dartdoc_vitepress/src/generator/vitepress/paths.dart';
import 'package:dartdoc_vitepress/src/model/model.dart';

/// Generates a Dart sidebar data file for Jaspr documentation sites.
class JasprSidebarGenerator {
  final VitePressPathResolver _paths;

  JasprSidebarGenerator(this._paths);

  /// Generates sidebar Dart source from the [PackageGraph].
  String generate(PackageGraph packageGraph) {
    final buf = StringBuffer();
    buf.writeln('// Generated by dartdoc_vitepress. Do not edit.');
    buf.writeln('// ignore_for_file: constant_identifier_names');
    buf.writeln();
    buf.writeln('class SidebarItem {');
    buf.writeln('  final String text;');
    buf.writeln('  final String link;');
    buf.writeln('  const SidebarItem({required this.text, required this.link});');
    buf.writeln('}');
    buf.writeln();
    buf.writeln('class SidebarGroup {');
    buf.writeln('  final String? title;');
    buf.writeln('  final List<SidebarItem> items;');
    buf.writeln('  const SidebarGroup({this.title, required this.items});');
    buf.writeln('}');
    buf.writeln();
    buf.writeln('const apiSidebarGroups = <SidebarGroup>[');

    for (final package in packageGraph.localPackages) {
      final libraries = package.libraries
          .where((lib) =>
              !isDuplicateSdkLibrary(lib, package.libraries) &&
              !isInternalSdkLibrary(lib))
          .toList()
        ..sort((a, b) => a.name.compareTo(b.name));

      if (libraries.isEmpty) continue;

      final isMultiPackage = packageGraph.localPackages.length > 1;
      final groupTitle =
          isMultiPackage ? _esc(package.name) : null;

      buf.writeln('  SidebarGroup(');
      if (groupTitle != null) {
        buf.writeln("    title: '$groupTitle',");
      }
      buf.writeln('    items: [');

      for (final lib in libraries) {
        final url = _paths.urlFor(lib);
        if (url == null) continue;
        buf.writeln("      SidebarItem(text: '${_esc(lib.name)}', link: '$url'),");
      }

      buf.writeln('    ],');
      buf.writeln('  ),');
    }

    buf.writeln('];');
    return buf.toString();
  }

  static String _esc(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}
