import 'package:jaspr/server.dart';
import 'package:jaspr_content/components/callout.dart';
import 'package:jaspr_content/components/code_block.dart';
import 'package:jaspr_content/components/github_button.dart';
import 'package:jaspr_content/components/header.dart';
import 'package:jaspr_content/components/image.dart';
import 'package:jaspr_content/components/sidebar.dart';
import 'package:jaspr_content/components/theme_toggle.dart';
import 'package:jaspr_content/jaspr_content.dart';
import 'package:jaspr_content/theme.dart';

import 'generated/api_sidebar.dart' as api;

void main() {
  Jaspr.initializeApp();

  runApp(
    Document(
      body: ContentApp(
        parsers: [MarkdownParser()],
        extensions: [
          HeadingAnchorsExtension(),
          TableOfContentsExtension(),
        ],
        components: [
          Callout(),
          CodeBlock(),
          Image(zoom: true),
        ],
        layouts: [
          DocsLayout(
            header: Header(
              title: '{{packageName}} API',
              logo: '/favicon.ico',
              items: [
                ThemeToggle(),
              ],
            ),
            sidebar: Sidebar(
              groups: [
                SidebarGroup(
                  links: [
                    SidebarLink(text: 'Overview', href: '/'),
                  ],
                ),
                // API sidebar generated by dartdoc_vitepress
                for (final group in api.apiSidebarGroups)
                  SidebarGroup(
                    title: group.title,
                    links: [
                      for (final item in group.items)
                        SidebarLink(text: item.text, href: item.link),
                    ],
                  ),
              ],
            ),
          ),
        ],
        theme: ContentTheme(
          primary: ThemeColor(ThemeColors.blue.$500, dark: ThemeColors.blue.$300),
          background: ThemeColor(ThemeColors.slate.$50, dark: ThemeColors.zinc.$950),
        ),
      ),
    ),
  );
}
